services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    platform: linux/amd64
    ports:
      - "4444:4444"
    deploy:
      resources:
        limits:
          memory: "2G"

  chrome:
    image: selenium/node-chrome:latest
    platform: linux/amd64
    shm_size: '2gb'
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PORT=4442
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1
    deploy:
      resources:
        limits:
          memory: "2G"

# run command: docker-compose -f docker-compose-grid.yml up --scale chrome=5 -d
# stop command: docker-compose -f docker-compose-grid.yml down
